### ISSUE TITLE
Provider not in the Terraform Registry

### ISSUE THREAD

**Issue by squarebracket** [llnw/terraform-provider-limelight#5]
Hashicorp now has a [terraform registry](https://registry.terraform.io/) akin to npm or docker hub. This provider should be published there for easy download by the community.

**Comment by colinbarr** [comment]
Thanks for raising this @squarebracket! It's already on our radar -- we just have a few final details to sort out before we publish there. Watch this space, it'll be happening soon.

**Comment by squarebracket** [comment]
Fair enough.

How about keeping this open until then so that I (and potentially others) can be notified when that's the case? Interrupts >>> polling.

**Comment by colinbarr** [comment]
Hello @squarebracket, just to let you know that we've now published our provider on the [Terraform Registry](https://registry.terraform.io/providers/llnw/limelight/latest).

**Comment by squarebracket** [comment]
Thanks for the ping.
